# Basic configuration
transaction_log      /var/log/btrbk.log
backend              btrfs-progs-sudo
stream_buffer        256m


volume /
    # The folder ON the root subvolume where snapshots live
    # Currently, we are storing snapshots in /var/.snapshots simply because it is easier...
    # Technically, it might be better to store them on the root subvolume to enable full rollbacks,
    # but then we would need to mount it first. I am mostly interested in rollbacking /home anyway.
    snapshot_dir var/.snapshots
    
    # Retention policy
    snapshot_preserve_min   1d
    snapshot_preserve       3d 
    
    ## The Subvolumes to backup

    # Snapshot /var/home (User data)
    subvolume /var/home
        snapshot_name home